# ==============================================================
# CONFIGURAÇÕES DE CONEXÃO COM O POSTGRESQL
# ==============================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/disconnect_db

# O usuário padrão do PostgreSQL (geralmente é postgres)
spring.datasource.username=postgres

spring.datasource.password=uma_senha_qualquer

# ==============================================================
# CONFIGURAÇÕES DO FLYWAY
# ==============================================================

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

# ==============================================================
# CONFIGURAÇÕES DO HIBERNATE (JPA) // Se for permitido no futuro (ainda em aberto)
# ==============================================================

spring.jpa.hibernate.ddl-auto=validate

# Mostra no terminal os comandos SQL que o Java está executando (ótimo para estudos)
spring.jpa.show-sql=true